version: '2.2'

services:

  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_USER: ${ELASTIC_USER:-}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      NETWORK_PUBLISH_HOST: ${ELASTIC_HOST:-}
      discovery.type: single-node
    networks:
      - elk

  logstash:
    image: logstash:8.4.3
    container_name: logstash
    volumes:
      - /var/log/GDPR/myapplication:/var/log/GDPR/myapplication:ro,Z
    ports:
      - 5044:5044
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      XPACK_MONITORING_ENABLED: 'false'
      CONFIG_STRING: 'input { rabbitmq { id => "rabbitmq_logs_1" host => "rabbitmq" port => 5672 vhost => "/" password => "guest" user => "guest" queue => "client.send_log_queue" exchange => "client" key => "client.client_routing" exchange_type => "direct" type => "rabbitmq" durable => true codec => "json" } } filter { json { source => "message" } mutate { remove_field => ["@version", "type", "event", "@timestamp"] } } output { elasticsearch { hosts => "elasticsearch:9200" user => "elastic" password => "changeme" index => "%{segment}" action => "index" } }'
    networks:
      - elk

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  rabbitmq_data:
  rabbitmq_log:
