version: '2.2'

services:

  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_USER: ${ELASTIC_USER:-}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      NETWORK_PUBLISH_HOST: ${ELASTIC_HOST:-}
      xpack.security.enabled: "true"
      discovery.type: single-node
    networks:
      - elk
  
  logstash:
    image: logstash:7.17.7
    container_name: logstash
    volumes:
      - /var/log/GDPR/myapplication:/var/log/GDPR/myapplication:ro,Z
    ports:
      - 5044:5044
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      XPACK_MONITORING_ENABLED: 'false'
      CONFIG_STRING: 'input { rabbitmq { host => "rabbitmq" port => 5672 vhost => "/" password => "password" user => "username" queue => "client.send_log_queue" exchange => "client" key => "client.client_routing" exchange_type => "direct" type => "rabbitmq" durable => true codec => "json" } } filter { json { source => "message" } mutate { remove_field => ["@version", "type", "event", "@timestamp"] } } output { elasticsearch { hosts => "elasticsearch:9200" user => "elastic" password => "test" index => "%{segment}" action => "index" } }'
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.17.7
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: ${ELASTIC_USER:-}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "username"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  rabbitmq_data:
  rabbitmq_log:
