version: '2.2'

services:

  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_USER: ${ELASTIC_USER:-}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
      network.publish_host: ${ELASTIC_HOST:-}
    networks:
      - elk

  logstash:
    image: logstash:8.4.3
    volumes:
      - /var/log/GDPR/myapplication:/var/log/GDPR/myapplication:ro,Z
      - ./logstash/pipeline/:/etc/logstash/
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    environment:
      LOGSTASH_INTERNAL_PASSWORD: ${ELASTIC_PASSWORD:-}
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_PORT: 9200
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: ${ELASTIC_USER:-}
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
      XPACK_MONITORING_ENABLED: "false"
      PATH_CONFIG: "/etc/logstash/*.conf"
      ELASTICSEARCH_HOST: ${ELASTIC_HOST:-}
      monitoring.elasticsearch.hosts: "http://elasticsearch:9200"
      # XPACK_MONITORING_RABBITMQ_HOST: "localhost"
      # XPACK_MONITORING_RABBITMQ_ID: "rabbitmq_logs_1"
      # XPACK_MONITORING_RABBITMQ_PORT: 5672
      # XPACK_MONITORING_RABBITMQ_VHOST: "/"
      # XPACK_MONITORING_RABBITMQ_PASSWORD: "teststst"\
    networks:
      - elk
    depends_on:
      - elasticsearch
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  rabbitmq_data:
  rabbitmq_log:
